### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by originallion** [gdhgdhgdh/mixxx-to-serato#1]
Thanks for making this project. I'm very new to working with this level of technology, but hope to give it my best shot! Any further tips on how to run the code is appreciated by this true newbie.....

Appreciating your sharing - Patrick

**Comment by gdhgdhgdh** [comment]
Hi Patrick,

To add support for Ogg audio, it could be as simple as changing line 107 from audio/mp3 to audio/ogg

The basic usage is as described in the README - install the `mutagen` module using `pip` and then just run the `cues.py` script. If none of that makes sense, then I can recommend https://www.python.org/about/gettingstarted/ to learn some basic concepts about installation. Good luck!
